site_name: Kangal
site_url: https://kangal.readthedocs.io/
repo_url: https://github.com/lichtwellenreiter/diy-kangal
repo_name: diy-kangal
site_author: lichtwellenreiter
theme:
  name: readthedocs
nav:
  - Welcome: 'index.md'
  - 'electronics.md'
  - 'assembly.md'
  - 'code.md'
  - 'config.md'
plugins:
    - with-pdf